spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:docker-eureka-server}

server:
  port: 8080

eureka:
  instance:
    hostname: ${springboot.app.name:docker-eureka-server}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
